export const magTekTags = Object.freeze({
    "DFDF56": "Encrypted Transaction Data KSN",
    "F0": "Transaction Results",
    "5F30": "Service Code",
    "DFDF59": "Encrypted Data Primitive",
    "DFDF54": "Mac KSN",
    "DFDF55": "MAC Encryption Type",
    "DFDF25": "IFD Serial Number",
    "FA": "Generic Data Container",
    "F1": "Status Data Container",
    "DFDF53": "Fallback Indicator",
    "DFDF4D": "Masked T2 PICC/ICC Data",
    "DFDF52": "Card Type",
    "F8": "Encrypted Data Container",
    "DFDF57": "Encryption Type",
    "DFDF58": "Number of padding bytes in Encrypted Data block",
    "DFDF36": "Encrypted Track 1 Status",
    "DFDF37": "Encrypted Track 1",
    "DFDF38": "Encrypted Track 2 Status",
    "DFDF39": "Encrypted Track 2",
    "DFDF3A": "Encrypted Track 3",
    "DFDF3B": "Encrypted Track 3",
    "DFDF3C": "Encrypted MagnePrint",
    "DFDF43": "MagnePrint Status",
    "DFDF50": "MSR KSN",
    "DFDF51": "MSR Encryption Type",
    "DFDF1A": "Transaction Status",
    "DFDF1B": "Additional Transaction Info",
    "F2": "Transaction Data Container",
    "F3": "Reversal Data Container",
    "F7": "Merchant Data Container",
    "5F25": "Application Effective Date",
    "5F24": "Application Expiration Date",
    "89": "Authorization Code",
    "5F2A": "Transaction Currency Code",
    "9F02": "Amount Authorized",
    "9F03": "Amount, Other",
    "9F06": "Application Identifier",
    "9F12": "Application Preferred Name",
    "9F1C": "Terminal Identification",
    "9F39": "POS Entry Mode",
    "9C": "Transaction Type",
    "9F34": "Cardholder Verification Results",
    "5F57": "Account Type",
    "5F20": "Cardholder Name",
    "DFDF4D": "Masked Track 2 PICC/ICC Data",
    "DFDF17": "EMV Transaction Result Message",
    "DFDF05": "Reversal Data",
    "DFDF06": "Online Response",
    "DFDF01": "Certificate Revocation List",
    "DFDF02": "Online Message for EMV Transaction",
    "DFDF20": "Terminal Features",
    "DFDF26": "EMV Database Level",
    "DFDF5B": "Terminal Capabilities for Purchase Transaction",
    "DFDF5C": "Terminal Capabilities for Cashback Transaction",
    "DFDF6E": "Terminal Capabilities for Payment Transaction",
    "DFDF75": "Terminal Capabilities for Inquiry",
    "DFDF76": "Terminal Capabilities for Transfer",
    "DFDF23": "ASI (Application Selection Indicator)",
    "DFDF10": "Threshold Value for Biased Random Selection",
    "DFDF11": "Target Percentage to be used for Random Selection",
    "DFDF12": "Maximum Target Percentage to be used for Biased Random Selection",
    "DFDF67": "MSR Fallback Supported",
    "DFDF68": "PIN Bypass Supported",
    "DFDF16": "Max Length of Issues Script",
    "F9": "MAC Structure and Generic Data Container",
    "70": "ARQC Container",
    "F4": "MSR Data Container",
    "9F1A": "Terminal Country Code",
    "5F36": "Transaction Currency Exponent",
    "9F4E": "Merchant Name and Location",
    "DFDF14": "Socket Timeout for Online Processing",
    "DFDF15": "Socket Retries",
    "DFDF19": "Default Terminal Language",
    "DFDF2D": "Supported Terminal Languages",
    "9F15": "Merchant Category Code",
    "9F16": "Merchant Identifier",
    "9F33": "Terminal Capabilities",
    "9F35": "Terminal Type",
    "9F3C": "Transaction Reference Code",
    "9F3D": "Transaction Currency Exponent",
    "9F40": "Additional Terminal Capabilities",
    "DF8122": "Terminal Action Code - Online",
    "84": "Dedicated File (DF) Name",
    "97": "Default TDOL",
    "9F01": "Acquirer Identifier",
    "9F09": "Application Version Number",
    "9F1B": "Terminal Floor Limit",
    "9F49": "Default DDOL",
    "DF8120": "Terminal Action Code - Default",
    "DF8121": "Terminal Action Code - Denial",
    "DFDF40": "Signature Required",
    "5F34" : "PAN Sequence Number"
});

//Country Codes:
//0840 <--USA
//0250 <--France
//0380 <--Italy
//0724 <--Spain
//0276 <--Germany

//Terminal Language Codes:
//656E <--English
//6672 <--French
//6974 <--Italian
//6465 <--German
//6573 <--Spanish